- name: Install Node.js on macOS
  import_tasks: macos.yml
  when: ansible_facts.os_family == "Darwin"
  tags: [nodejs]

- name: Install Node.js on Debian-based systems
  import_tasks: debian.yml
  when: ansible_facts.os_family == "Debian"
  tags: [nodejs]

- name: Install Node.js on Arch Linux
  import_tasks: arch.yml
  when: ansible_facts.os_family == "Archlinux"
  tags: [nodejs]

- name: Verify node and nodejs
  command: "{{ item }}"
  loop:
    - node --version
    - nodejs --version
  register: node_check
  changed_when: false
  tags: [nodejs]

