- name: Bootstrap local machine
  hosts: localhost
  connection: local

  roles:
    - core
    - fonts
    - bash
    - zsh
    - dotfiles
    - nodejs
    - go
    - gemini_cli
    - terminal
    - neovim
